# Site settings
title: Amrit Srivastava
description: Amrit Srivastava
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Amrit Srivastava
user_title: Full Stack Developer
email: srivastava.amrit1999@gmail.com
linkedin_username: amrit-srivastava
twitter_username: hi_amrit
salesforce_username: amritsrivastava
github_username: amritsrivastava
medium_username: srivastava.amrit1999

# Google-analytics
google-analytics:
  id: ''

exclude: ['package.json', 'src', 'node_modules']
